### ISSUE TITLE
[Meteor 1.3] Imported CSS modules

### ISSUE THREAD

**Issue by szchenghuang** [sebakerckhof/meteor-minifiers-autoprefix#1]
Does this package minify/autoprefix a CSS module when it is imported by a JS? In my case, both the CSS and JS are located in a imports directory. I wish the imported CSS can be minified and autoprefixed, but I can't get it work.

I output paths of files processed by the CSS minifier in the build process, and observed that the imported CSS module are not reached to the CSS minifier. With more digging, this commit 12c946ee651a93725f243f790c7919de3d445a19 enables lazy CSS import. It turns the CSS module into a `<script>` node on the HTML document. My guess is that by the commit an imported CSS module is not collected for Meteor CSS tools.

**Comment by sebakerckhof** [comment]
No, it only works for CSS that is being processed by the meteor build tool.

**Comment by szchenghuang** [comment]
Thanks for confirmation.
