### ISSUE TITLE
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

### ISSUE THREAD

**Issue by yched** [sebakerckhof/meteor-minifiers-autoprefix#13]
We recently started seeing this message on meteor run / meteor build

> Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

Would bumping autoprefixer solve the issue ?
(latest is 9.5.0, meteor-minifiers-autoprefix uses 7.0.5)

**Comment by copleykj** [comment]
This is the nature of packages that have NPM dependencies. npm-shrinkwrap.json causes the exact versions to be installed and nothing more.

I'll see about getting a PR submitted for this.

**Comment by yched** [comment]
bump ?

**Comment by sebakerckhof** [comment]
Just released version 2.0.0 which updates dependencies and should have some performance improvements as well.

**Comment by yched** [comment]
Awesome :tada: 
Thanks @sebakerckhof !
